name: Weekly Match Schedule & Reminder

on:
  schedule:
    - cron: '55 16 * * 3'  # Wednesday 11:55 AM EST
  workflow_dispatch:

jobs:
  scrape_schedule:
    name: Scrape Latest Schedule
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 python-dotenv

      - name: Run scraper
        env:
          URL: ${{ secrets.URL }}
          TEAM_NAME: ${{ secrets.TEAM_NAME }}
        run: python scrape_schedule.py

  send_reminders:
    name: Send WhatsApp Match Reminders
    needs: scrape_schedule  # wait for scraper to finish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install twilio python-dotenv

      - name: Send reminders
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
          TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
        run: python send_reminders.py
